services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - seafile-db-data:/var/lib/mysql
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--mariadbupgrade", "--innodb_initialized"]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  memcached:
    image: memcached:1.6
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  seafile:
    image: seafileltd/seafile-mc:${SEAFILE_IMAGE_VERSION:-12.0-latest}
    container_name: seafile
    restart: unless-stopped
    volumes:
      - seafile-shared-data:/shared
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - seafile-net
      - proxy-net
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    container_name: seafile-oods
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET:-Supers3cr3t}
    networks:
      - seafile-net
      - proxy-net
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - seafile
      - onlyoffice-documentserver
    networks:
      - proxy-net

networks:
  seafile-net:
    name: seafile-net
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
  proxy-net:
    name: proxy-net
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16

volumes:
  seafile-db-data:
  seafile-shared-data: