version: '3.6'

services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ${SEAFILE_DB_DATA:-./data/db}:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.9
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: h44z/seafile-ce:${SEAFILE_VERSION:-8.0.4}
    container_name: seafile
    restart: unless-stopped
    ports:
      - "${SEAHUB_PORT:-8000}:8000"
      - "${SEAFILE_PORT:-8082}:8082"
      - "${SEAFDAV_PORT:-8080}:8080"
    volumes:
      - ${SEAFILE_SHARED_DATA:-./data/seafile}:/seafile
    env_file:
      - .env
    depends_on:
      - memcached
    networks:
      - seafile-net
      - ldap-net  # Remove this network if LDAP is not used

  # Remove this section if you do not want to use only office integration
  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    container_name: seafile-oods
    ports:
      - "${ONLYOFFICE_PORT:-8081}:80"
    volumes:
      - ${ONLYOFFICE_CONFIG:-./data/onlyoffice/local.conf}:/etc/onlyoffice/documentserver/local.json
    networks:
      - seafile-net

networks:
  seafile-net:
    name: seafile-net
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
  ldap-net:  # Remove this network if LDAP is not used
    external:
      name: ldap-net
